# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# and this guide: https://towardsdatascience.com/travis-ci-for-r-advanced-guide-719cb2d9e0e5

env:
    - PKG_TARBALL=shapley_0.1.0.tar.gz

language: r
  
matrix:
  include:
  - r: oldrel
    script:
      - R CMD build .
      - R CMD check *tar.gz --as-cran 
  - r: release
    script:
      - R CMD build .
      - R CMD check *tar.gz --as-cran 
  - r: devel
    script:
      - R CMD build .
      - R CMD check *tar.gz --as-cran 
  - r: release
    os: osx
    osx_image: xcode7.3
    script:
      - brew untap homebrew/homebrew-cask-drivers
      - brew reinstall cask
      - R CMD build .
      - R CMD check *tar.gz --as-cran

# For code coverage
r_github_packages:
  - r-lib/covr
  
after_success:
      - tar -C .. -xf $PKG_TARBALL
      - xvfb-run Rscript -e 'covr::codecov(type=c("tests", "vignettes", "examples"))'